In [2]:
import pyedflib
import numpy as np
import pandas as pd

In [2]:
f = pyedflib.EdfReader('S001R03.edf')
n = f.signals_in_file
signal_labels = f.getSignalLabels()
sigbufs = np.zeros((n, f.getNSamples()[0]))
for i in np.arange(n):
        sigbufs[i, :] = f.readSignal(i)

In [6]:
sigbufs

array([[ -57.,  -49.,  -55., ...,    0.,    0.,    0.],
       [ -13.,  -11.,  -17., ...,    0.,    0.,    0.],
       [ -15.,  -10.,  -16., ...,    0.,    0.,    0.],
       ...,
       [ -56.,  -70.,  -77., ...,    0.,    0.,    0.],
       [-124., -149., -153., ...,    0.,    0.,    0.],
       [ -28.,  -40.,  -37., ...,    0.,    0.,    0.]])

In [9]:
f.readAnnotations()

(array([  0. ,   4.2,   8.3,  12.5,  16.6,  20.8,  24.9,  29.1,  33.2,
         37.4,  41.5,  45.7,  49.8,  54. ,  58.1,  62.3,  66.4,  70.6,
         74.7,  78.9,  83. ,  87.2,  91.3,  95.5,  99.6, 103.8, 107.9,
        112.1, 116.2, 120.4]),
 array([4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2,
        4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1, 4.2, 4.1,
        4.2, 4.1, 4.2, 4.1]),
 array(['T0', 'T2', 'T0', 'T1', 'T0', 'T1', 'T0', 'T2', 'T0', 'T2', 'T0',
        'T1', 'T0', 'T1', 'T0', 'T2', 'T0', 'T1', 'T0', 'T2', 'T0', 'T2',
        'T0', 'T1', 'T0', 'T1', 'T0', 'T2', 'T0', 'T1'], dtype='<U2'))

In [5]:
print(signal_labels)

['Fc5.', 'Fc3.', 'Fc1.', 'Fcz.', 'Fc2.', 'Fc4.', 'Fc6.', 'C5..', 'C3..', 'C1..', 'Cz..', 'C2..', 'C4..', 'C6..', 'Cp5.', 'Cp3.', 'Cp1.', 'Cpz.', 'Cp2.', 'Cp4.', 'Cp6.', 'Fp1.', 'Fpz.', 'Fp2.', 'Af7.', 'Af3.', 'Afz.', 'Af4.', 'Af8.', 'F7..', 'F5..', 'F3..', 'F1..', 'Fz..', 'F2..', 'F4..', 'F6..', 'F8..', 'Ft7.', 'Ft8.', 'T7..', 'T8..', 'T9..', 'T10.', 'Tp7.', 'Tp8.', 'P7..', 'P5..', 'P3..', 'P1..', 'Pz..', 'P2..', 'P4..', 'P6..', 'P8..', 'Po7.', 'Po3.', 'Poz.', 'Po4.', 'Po8.', 'O1..', 'Oz..', 'O2..', 'Iz..']


In [8]:
np.random.rand(120, 64)

array([[1.17212826e-01, 7.89865072e-01, 3.28104122e-01, ...,
        3.86472268e-01, 3.69335047e-01, 1.41641529e-01],
       [1.42593227e-01, 6.87057279e-01, 6.84998994e-03, ...,
        3.98792031e-01, 5.02719082e-01, 7.11478231e-01],
       [4.80823039e-01, 7.52651049e-01, 3.18079401e-01, ...,
        8.96344889e-02, 9.96336701e-01, 5.65946850e-01],
       ...,
       [8.38644708e-01, 3.22985311e-01, 3.62056661e-01, ...,
        4.97740455e-01, 7.51389677e-01, 6.18989545e-01],
       [6.83782077e-01, 8.37704980e-01, 9.82935937e-01, ...,
        4.21347313e-01, 6.08578870e-01, 1.45124470e-01],
       [8.81731538e-01, 9.26092065e-01, 3.89016607e-01, ...,
        2.41020750e-01, 2.90063645e-04, 3.42974555e-01]])

In [6]:
import urllib.request
import numpy as np
import pyedflib

timeArray = np.array([round(x,5) for x in np.arange(0,120,.00625)])
timeArray = timeArray.reshape(19200,1)
reader = pyedflib.EdfReader('S001R03.edf') # convert this to a function or some shit and loop through bro. and remember to reader.close()
annotations = reader.readAnnotations()
intervals = np.append(annotations[0],[120])
codes = annotations[2]
codeArray = []     
counter = 1
for timeVal in timeArray:
    if timeVal == 120:
        break
    elif timeVal / intervals[counter] == 1.0:
        counter += 1

    codeArray.append(codes[counter - 1])

invertCodeArray = np.array(codeArray).reshape(19200,1)
numSignals = reader.signals_in_file
signal_labels = reader.getSignalLabels()
dataset = np.zeros((numSignals, reader.getNSamples()[0]))
print(dataset.shape)
for signal in np.arange(numSignals):
    dataset[signal, :] = reader.readSignal(signal)

dataset = dataset[:,:-800].transpose()
masterSet = np.concatenate((timeArray,invertCodeArray,dataset),axis=1)


(64, 20000)


In [7]:
masterSet

array([['0.0', 'T0', '-57.0', ..., '-56.0', '-124.0', '-28.0'],
       ['0.00625', 'T0', '-49.0', ..., '-70.0', '-149.0', '-40.0'],
       ['0.0125', 'T0', '-55.0', ..., '-77.0', '-153.0', '-37.0'],
       ...,
       ['119.98125', 'T0', '7.0', ..., '81.0', '87.0', '52.0'],
       ['119.9875', 'T0', '-5.0', ..., '74.0', '80.0', '48.0'],
       ['119.99375', 'T0', '-22.0', ..., '57.0', '68.0', '29.0']],
      dtype='<U32')

In [9]:
pd.DataFrame(masterSet).to_csv("data.csv")